### ISSUE TITLE
have you compare relative energy between D4FT and JAX SCF;  JAX-XC is JAX-SCF? 

### ISSUE THREAD

**Issue by Eipgen** [sail-sg/jax_xc#26]
Hi, Dear Develpers
Recently I read you article[https://arxiv.org/abs/2303.00399](url), it's very inspirational

1. first my problem is JAX-SCF  renamed JAX-XC now?
2. it seems the DFT4 have a better SCF convergence. so I want to use it to do some tests on strong correlation systems.  The link [https://github.com/sail-sg/d4ft](url) the article seems death ?
3. have you compare some relative energy tests?

**Comment by DyeKuu** [comment]
Hi @Eipgen ! Thank you for your interest in the work. Sharing my answers and thoughts below. Feel free to add more comments if it is not clear.

1. No, jax-xc is a more specific library aiming to make all the xc functionals differentiable in Jax framework. The motivation of this library indeed comes from the D4FT work that you've mentioned, in which only simple xc functionals such as LDA that could be hand-implemented in Jax are included. And we wanted a way to "sync" with libxc without manually porting all the xc functionals in Jax so here is born the jax-xc. jax-scf is a baseline compared in d4ft, in which the scf loop is re-implemented in Jax fashion.
2. There has long been an effort undergoing to open source d4ft since last year and this effort has been continuing at least till March 2023 when I was still in SAIL. The link points to a private repo yet for now: Instead of providing a piece of messy repo just signifying that "our code is here, take it and run it. That's all", the idea is more of "we want this code to be production-level clean, fast, and ready-to-use for the community". This comes with time and with more features added on top of the published version. The timeline should be soon as I've seen that the commits days ago are major refactor for the preparation of open source.
3. Not sure I understand this question as I'm more from the CS background. Could you say more about the "relative energy tests"? Is it the same as "put it in a real system and see what is the difference of energy"?
  
cc @mavenlin @Szkered @nicktianboli

**Comment by Eipgen** [comment]
Thank you very much for your answer,
3. In practical applications, chemists pay more attention to the comparison of relative energies, such as reaction energy (E_product -E_reactant). There are many such standard datasets contain relative energy, GMTKN55, MGCDB.
